const state={dinnerTime:localStorage.getItem('bfDinnerTime')||'19:30',guests:Number(localStorage.getItem('bfGuests')||8),notes:localStorage.getItem('bfChefNotes')||''};
const $=id=>document.getElementById(id);
function serviceText(){return `${state.dinnerTime} · ${state.guests} guests`}
function goHome(){closeSheet();closeSage();scrollTo({top:0,behavior:'smooth'})}
function openSheet(key){$('sheetBody').innerHTML=screen(key);$('sheet').classList.add('open')}
function closeSheet(){$('sheet').classList.remove('open')}
function openSage(){closeSheet();$('sage').classList.add('open');syncSage()}
function closeSage(){stopListening();$('sage').classList.remove('open')}
function syncSage(){if($('dinnerTime'))$('dinnerTime').textContent=serviceText()}
function toast(msg){let n=document.createElement('div');n.className='toast';n.textContent=msg;document.body.appendChild(n);setTimeout(()=>n.remove(),1800)}
function saveNotes(){state.notes=($('chefNotes')?.value||'').trim();localStorage.setItem('bfChefNotes',state.notes);toast('Chef note saved')}
function clearNotes(){state.notes='';localStorage.removeItem('bfChefNotes');openSheet('notes')}
function updateGuests(){let n=prompt('Number of guests',state.guests);if(n===null)return;n=Number(n);if(!Number.isFinite(n)||n<1||n>50)return toast('Enter 1–50 guests');state.guests=Math.round(n);localStorage.setItem('bfGuests',state.guests);openSheet('charters');syncSage()}
function screen(k){const s={
notifications:`<h2>Notifications</h2><p>Only changes that affect the Chef's day or need a decision appear here.</p><div class='row'><span>Provisioning</span><b class='red'>2 items low</b></div><div class='row'><span>Sea bass delivery</span><b class='gold'>Due now</b></div><div class='row'><span>Guest preference</span><b class='blue'>Updated</b></div>`,
profile:`<h2>Chef Profile</h2><div class='row'><span>Role</span><b>Chef</b></div><div class='row'><span>Location</span><b>Antibes, France</b></div><div class='row'><span>Working mode</span><b class='green'>Live test</b></div><p>Profile, yacht assignment, security and preferences live here.</p>`,
services:`<h2>Today's Service</h2><div class='row'><span>Breakfast · 08:30</span><b class='green'>Complete</b></div><div class='row'><span>Lunch · 13:00</span><b class='green'>Complete</b></div><div class='row'><span>Dinner</span><b class='gold'>${serviceText()}</b></div><div class='row'><span>Snacks</span><b class='blue'>On request</b></div><h3>Next action</h3><div class='card'><b>17:00 · Prepare garnishes</b><p>5 min allocated</p></div><div class='actions'><button class='btn' onclick="openSheet('sequence')">Service Sequence</button><button class='btn ghost' onclick='openSage()'>Ask SAGE</button></div>`,
sequence:`<h2>Service Sequence</h2><p>Dinner ${serviceText()} · actual clock times</p><div class='row'><span>18:30</span><b>Beurre blanc mise en place</b></div><div class='row'><span>18:40</span><b>Prepare vegetables</b></div><div class='row'><span>18:50</span><b>Set fish station</b></div><div class='row'><span>19:00</span><b>Check pass / sauces</b></div><div class='row'><span>19:10</span><b>Long-lead components</b></div><div class='row'><span>19:18</span><b>Fire vegetables</b></div><div class='row'><span>19:22</span><b>Fire proteins</b></div><div class='row'><span>19:27</span><b>Finish sauces</b></div><div class='row'><span>19:29</span><b>Final pass</b></div><div class='row'><span>${state.dinnerTime}</span><b class='gold'>SERVE</b></div><div class='actions'><button class='btn' onclick="openSheet('chefmode')">Start Chef Mode</button></div>`,
chefmode:`<h2>Chef Mode</h2><div class='badge'>FOCUSED WORKSPACE</div><div class='card'><div class='small'>CURRENT STEP · 19:22</div><h2>FIRE SEA BASS</h2><p>Heat pan medium-high. Add 10 ml oil. Skin side down, press 20 sec, cook 3 min, turn, add butter/thyme/garlic, baste 90 sec, check temperature, rest 2 min.</p><div class='row'><span>Next</span><b>Plate courgettes</b></div></div><div class='actions'><button class='btn' onclick="toast('Step marked complete')">Mark complete</button><button class='btn ghost' onclick='openSage()'>Voice with SAGE</button></div>`,
provisioning:`<h2>Smart Provisioning</h2><div class='row'><span>Burrata</span><b class='red'>High priority · low stock</b></div><div class='row'><span>Sea bass</span><b class='gold'>Delivery due</b></div><div class='row'><span>Micro herbs</span><b class='green'>Use today</b></div><h3>Smart recommendation</h3><p>Resolve Burrata first because it affects the active menu and has the shortest operational lead time.</p>`,
guests:`<h2>Guest Preferences</h2><div class='row'><span>Guest count</span><b>${state.guests}</b></div><div class='row'><span>Preference update</span><b class='blue'>1 new</b></div><p>Changes affecting menus, allergies or service update connected planning.</p>`,
weather:`<h2>Weather Update</h2><div class='row'><span>Antibes, France</span><b>24°C</b></div><div class='row'><span>Sea state</span><b class='green'>Calm</b></div><p>Weather is elevated only when it affects service, provisioning or passage.</p>`,
dashboard:`<h2>Dashboard</h2><p><b>What do I need to deal with right now?</b></p><div class='row'><span>DO NOW</span><b>Prepare garnishes</b></div><div class='row'><span>COMING UP</span><b>Dinner ${state.dinnerTime}</b></div><div class='row'><span>PLAN AHEAD</span><b>Tomorrow's provisioning</b></div><div class='actions'><button class='btn' onclick="openSheet('chefmode')">Chef Mode</button></div>`,
charters:`<h2>Charters</h2><div class='row'><span>Current day</span><b class='green'>Active</b></div><div class='row'><span>Guests</span><b>${state.guests}</b></div><div class='row'><span>Dinner</span><b>${state.dinnerTime}</b></div><p>Full setup will connect journey, guests, preferences, services, budget and provisioning.</p><div class='actions'><button class='btn' onclick='updateGuests()'>Change guest count</button></div>`,
quickadd:`<h2>Quick Add</h2><p>Add something without leaving the working flow.</p><div class='actions'><button class='btn' onclick="toast('Stock item added for test')">Stock item</button><button class='btn ghost' onclick="openSheet('notes')">Chef note</button><button class='btn ghost' onclick="toast('Task added for test')">Task</button><button class='btn ghost' onclick="openSheet('services')">Service update</button></div>`,
notes:`<h2>Chef Notes</h2><p>Private operational notes for the working day.</p><textarea id='chefNotes' class='field' rows='7' placeholder='Add a note…'>${(state.notes||'').replaceAll('&','&amp;').replaceAll('<','&lt;')}</textarea><div class='actions'><button class='btn' onclick='saveNotes()'>Save note</button><button class='btn ghost' onclick='clearNotes()'>Clear</button></div>`,
more:`<h2>More</h2><div class='row'><span>Chef Mode</span><button class='btn ghost' onclick="openSheet('chefmode')">Open</button></div><div class='row'><span>Guest Memory</span><button class='btn ghost' onclick="openSheet('guests')">Open</button></div><div class='row'><span>Chef Notes</span><button class='btn ghost' onclick="openSheet('notes')">Open</button></div><div class='row'><span>Settings & security</span><b>Prototype</b></div>`};return s[k]||'<h2>Coming next</h2>'}
let recognition,listening=false;
function speak(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-GB';u.rate=.98;speechSynthesis.speak(u)}catch(e){}}
function stopListening(){if(recognition)try{recognition.stop()}catch(e){}listening=false;$('sageOrb')?.classList.remove('listening')}
function startListening(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return $('sageStatus').textContent='Voice recognition is not supported in this browser.';if(listening)return;recognition=new SR();recognition.lang='en-GB';recognition.interimResults=false;recognition.continuous=false;recognition.onstart=()=>{listening=true;$('sageOrb').classList.add('listening');$('sageStatus').textContent='Listening…'};recognition.onend=()=>{listening=false;$('sageOrb').classList.remove('listening');$('sageStatus').textContent='Tap SAGE to speak again'};recognition.onerror=e=>$('sageStatus').textContent='Microphone: '+e.error;recognition.onresult=e=>handleCommand(e.results[0][0].transcript);recognition.start()}
function handleCommand(text){const q=text.toLowerCase().trim();let reply='I heard you, Chef.';$('transcript').innerHTML=`<b>Chef:</b> ${text}`;if(/\b(hello|hi|hey)\s+(sage|saj|stage)\b/.test(q)||q==='sage')reply='Hello, Chef. I’m here. What do you need?';else if(q.includes("what's next")||q.includes('what is next'))reply='Next action is prepare garnishes at 17:00. Five minutes allocated.';else if(q.includes('services today')||q.includes("today's services")||q.includes('todays services'))reply=`Breakfast and lunch are complete. Dinner is at ${serviceText()}. Snacks are on request.`;else if(q.includes('chef mode')){reply='Opening Chef Mode.';setTimeout(()=>{closeSage();openSheet('chefmode')},700)}else if(q.includes('provisioning')){reply='Opening Smart Provisioning.';setTimeout(()=>{closeSage();openSheet('provisioning')},700)}else{const m=q.match(/(?:move|change|set).*dinner.*?(\d{1,2})(?::(\d{2}))?/);if(m){let h=+m[1],min=m[2]||'00';if(h<12&&/pm|evening|dinner/.test(q))h+=12;state.dinnerTime=String(h).padStart(2,'0')+':'+min;localStorage.setItem('bfDinnerTime',state.dinnerTime);syncSage();reply=`Dinner moved to ${state.dinnerTime}. I will recalculate the connected prep sequence.`}}$('transcript').innerHTML+=`<br><br><b class='gold'>SAGE:</b> ${reply}`;$('sageStatus').textContent='Ready';speak(reply)}