(function(global){
'use strict';
const core=global.BusinessFlowCore;if(!core)return;
const clone=v=>JSON.parse(JSON.stringify(v));
const uid=p=>`${p}_${Math.random().toString(36).slice(2,9)}_${Date.now().toString(36)}`;
const library={
Mediterranean:[
{name:'Greek yoghurt, berries & pistachio granola',meal:'breakfast',tags:['vegetarian'],allergens:['dairy','nuts']},{name:'Herb omelette, tomatoes & sourdough',meal:'breakfast',tags:['vegetarian'],allergens:['eggs','gluten']},{name:'Citrus sea bass, fennel & new potatoes',meal:'lunch',tags:['fish'],allergens:['fish']},{name:'Lemon chicken, charred courgette & couscous',meal:'lunch',tags:['poultry'],allergens:['gluten']},{name:'Watermelon, mint & feta cups',meal:'snack',tags:['vegetarian'],allergens:['dairy']},{name:'Seasonal fruit & coconut yoghurt',meal:'snack',tags:['vegan'],allergens:[]},{name:'Pan-roasted sea bass, beurre blanc & vegetables',meal:'dinner',tags:['fish'],allergens:['fish','dairy']},{name:'Herb lamb loin, aubergine & tomato jus',meal:'dinner',tags:['meat'],allergens:[]}],
'Modern European':[
{name:'Poached eggs, spinach & rye toast',meal:'breakfast',tags:['vegetarian'],allergens:['eggs','gluten']},{name:'Apple bircher, seeds & berries',meal:'breakfast',tags:['vegetarian'],allergens:['gluten']},{name:'Roast salmon, peas, asparagus & dill',meal:'lunch',tags:['fish'],allergens:['fish']},{name:'Chicken supreme, crushed potatoes & greens',meal:'lunch',tags:['poultry'],allergens:[]},{name:'Berry smoothie & oat bites',meal:'snack',tags:['vegetarian'],allergens:['gluten']},{name:'Crudités, hummus & seeded crackers',meal:'snack',tags:['vegan'],allergens:['sesame','gluten']},{name:'Beef fillet, pommes purée & red wine jus',meal:'dinner',tags:['meat'],allergens:['dairy']},{name:'Roast cod, leeks & herb velouté',meal:'dinner',tags:['fish'],allergens:['fish','dairy']}],
'Light & Fresh':[
{name:'Chia, mango & lime breakfast pot',meal:'breakfast',tags:['vegan'],allergens:[]},{name:'Fresh fruit, yoghurt & toasted seeds',meal:'breakfast',tags:['vegetarian'],allergens:['dairy']},{name:'Grilled tuna, tomato, olive & herb salad',meal:'lunch',tags:['fish'],allergens:['fish']},{name:'Chicken, avocado & citrus salad',meal:'lunch',tags:['poultry'],allergens:[]},{name:'Frozen grapes, berries & melon',meal:'snack',tags:['vegan'],allergens:[]},{name:'Cucumber cups with avocado & herbs',meal:'snack',tags:['vegan'],allergens:[]},{name:'Grilled prawns, courgette ribbons & lemon',meal:'dinner',tags:['shellfish'],allergens:['shellfish']},{name:'Herb chicken, ratatouille & basil oil',meal:'dinner',tags:['poultry'],allergens:[]}]
};
const nightLibrary={
'Fine Dining':[
{name:'Beef fillet, truffle pomme purée & red wine jus',meal:'dinner',tags:['meat','fine-dining'],allergens:['dairy']},{name:'Sea bass, beurre blanc, asparagus & caviar',meal:'dinner',tags:['fish','fine-dining'],allergens:['fish','dairy']},{name:'Lamb loin, aubergine, confit tomato & jus',meal:'dinner',tags:['meat','fine-dining'],allergens:[]}],
'Mediterranean Night':[
{name:'Whole roasted sea bass, lemon, oregano & potatoes',meal:'dinner',tags:['fish','mediterranean'],allergens:['fish']},{name:'Herb lamb, grilled aubergine, tomato & olive',meal:'dinner',tags:['meat','mediterranean'],allergens:[]},{name:'Charred prawns, courgette, lemon & basil',meal:'dinner',tags:['shellfish','mediterranean'],allergens:['shellfish']}],
'Italian Night':[
{name:'Wild mushroom risotto, parmesan & herbs',meal:'dinner',tags:['vegetarian','italian'],allergens:['dairy']},{name:'Sea bass acqua pazza, tomato & basil',meal:'dinner',tags:['fish','italian'],allergens:['fish']},{name:'Beef tagliata, rocket, parmesan & balsamic',meal:'dinner',tags:['meat','italian'],allergens:['dairy']}],
'Greek Night':[
{name:'Grilled sea bream, lemon potatoes & horta',meal:'dinner',tags:['fish','greek'],allergens:['fish']},{name:'Lamb souvlaki, tzatziki & village salad',meal:'dinner',tags:['meat','greek'],allergens:['dairy']},{name:'Stuffed peppers, feta & herbs',meal:'dinner',tags:['vegetarian','greek'],allergens:['dairy']}],
'Seafood Night':[
{name:'Grilled lobster, herb butter & seasonal vegetables',meal:'dinner',tags:['shellfish','seafood'],allergens:['shellfish','dairy']},{name:'Pan-roasted local fish, shellfish broth & fennel',meal:'dinner',tags:['fish','shellfish','seafood'],allergens:['fish','shellfish']},{name:'Prawn, scallop & courgette grill',meal:'dinner',tags:['shellfish','seafood'],allergens:['shellfish']}],
'BBQ & Grill Night':[
{name:'Charcoal beef fillet, peppers & chimichurri',meal:'dinner',tags:['meat','grill'],allergens:[]},{name:'Grilled chicken, corn, courgette & herb dressing',meal:'dinner',tags:['poultry','grill'],allergens:[]},{name:'Grilled local fish, lemon & fire-roasted vegetables',meal:'dinner',tags:['fish','grill'],allergens:['fish']}],
'Asian Fusion Night':[
{name:'Miso glazed salmon, sesame greens & rice',meal:'dinner',tags:['fish','asian'],allergens:['fish','soy','sesame']},{name:'Ginger chicken, coconut rice & pak choi',meal:'dinner',tags:['poultry','asian'],allergens:['soy']},{name:'Prawn, lime & chilli noodles',meal:'dinner',tags:['shellfish','asian'],allergens:['shellfish','gluten']}],
'Local Port Night':[
{name:'Chef’s local market fish, seasonal vegetables & herbs',meal:'dinner',tags:['fish','local'],allergens:['fish']},{name:'Local butcher’s cut, market vegetables & jus',meal:'dinner',tags:['meat','local'],allergens:[]},{name:'Market vegetable tasting plate',meal:'dinner',tags:['vegetarian','local'],allergens:[]}]
};
const nightThemes=['Chef’s Choice',...Object.keys(nightLibrary)];
function normal(v){return String(v||'').trim().toLowerCase();}
function activeAllergies(state){return new Set((state.guests?.allergySummary||[]).map(a=>normal(a.label)));}
function conflicts(dish,allergies){return(dish.allergens||[]).some(a=>allergies.has(normal(a)));}
function allLibrary(){const out=[];Object.entries(library).forEach(([theme,dishes])=>dishes.forEach(d=>out.push({...clone(d),theme})));Object.entries(nightLibrary).forEach(([theme,dishes])=>dishes.forEach(d=>out.push({...clone(d),theme,nightTheme:theme})));return out;}
function sourceFocus(dish){const tags=new Set((dish.tags||[]).map(normal)),name=normal(dish.name),focus=[];if(tags.has('fish')||tags.has('shellfish')||/fish|salmon|cod|tuna|prawn|sea bass|bream|lobster|scallop/.test(name))focus.push('Protein','Seafood');if(tags.has('poultry')||/chicken|turkey/.test(name))focus.push('Protein','Poultry');if(tags.has('meat')||/lamb|beef|venison/.test(name))focus.push('Protein','Meat');if(tags.has('vegetarian')||tags.has('vegan')||/fruit|vegetable|salad|courgette|tomato|berries|mango|melon|avocado|pepper/.test(name))focus.push('Produce');if(/yoghurt|feta|butter|egg|parmesan/.test(name))focus.push('Chilled');if(/bread|toast|granola|oat|couscous|cracker|rice|noodle/.test(name))focus.push('Dry Store');return[...new Set(focus)];}
function materialize(d){return{id:uid('dish'),name:d.name,meal:d.meal,tags:clone(d.tags||[]),allergens:clone(d.allergens||[]),status:'draft',locked:false,sourceFocus:sourceFocus(d),theme:d.theme||'',nightTheme:d.nightTheme||''};}
function chooseFrom(pool,index,allergies){const safe=pool.filter(d=>!conflicts(d,allergies)),usable=safe.length?safe:pool;if(!usable.length)return null;return materialize(usable[index%usable.length]);}
function choose(theme,meal,index,allergies){const source=(library[theme]||library.Mediterranean).filter(d=>d.meal===meal);return chooseFrom(source,index,allergies)||{id:uid('dish'),name:`Chef's ${meal}`,meal,allergens:[],status:'draft',locked:false};}
function chooseDinner(overallTheme,nightTheme,index,allergies){if(nightTheme&&nightTheme!=='Chef’s Choice'&&nightLibrary[nightTheme])return chooseFrom(nightLibrary[nightTheme],index,allergies);return choose(overallTheme,'dinner',index,allergies);}
function buildDraft(theme){const state=core.getState(),days=Math.max(1,core.charterDays?core.charterDays():1),allergies=activeAllergies(state),menuDays=[];for(let i=0;i<days;i++){const date=state.charter.startDate?new Date(`${state.charter.startDate}T00:00:00Z`):null;if(date)date.setUTCDate(date.getUTCDate()+i);const nightTheme='Chef’s Choice';menuDays.push({id:`day_${i+1}`,day:i+1,date:date?date.toISOString().slice(0,10):'',nightTheme,meals:{breakfast:[choose(theme,'breakfast',i,allergies)],lunch:[choose(theme,'lunch',i,allergies)],snack:[choose(theme,'snack',i,allergies)],dinner:[chooseDinner(theme,nightTheme,i,allergies)]}});}return{status:'draft',theme,days:menuDays,lockedDishIds:[]};}
function saveState(nextState){nextState.audit=Array.isArray(nextState.audit)?nextState.audit:[];nextState.audit.unshift({id:uid('audit'),at:new Date().toISOString(),deviceId:nextState.sync?.deviceId||'device_browser',action:'menu.updated',detail:{theme:nextState.menu?.theme||'',days:nextState.menu?.days?.length||0}});core.importData({state:nextState});return core.getState().menu;}
function generate(theme){const state=core.getState();state.menu=buildDraft(theme||state.menu?.theme||'Mediterranean');return saveState(state);}
function setTheme(theme){if(!library[theme])throw new Error('Unknown menu theme');const state=core.getState();state.menu.theme=theme;return saveState(state);}
function findDishContext(state,dishId){for(const day of state.menu?.days||[]){for(const[meal,items]of Object.entries(day.meals||{})){const dish=(items||[]).find(d=>d.id===dishId);if(dish)return{day,meal,dish};}}return null;}
function toggleLock(dishId){const state=core.getState(),ctx=findDishContext(state,dishId);if(!ctx)throw new Error('Dish not found');ctx.dish.locked=!ctx.dish.locked;state.menu.lockedDishIds=state.menu.lockedDishIds||[];state.menu.lockedDishIds=ctx.dish.locked?[...new Set([...state.menu.lockedDishIds,dishId])]:state.menu.lockedDishIds.filter(id=>id!==dishId);return saveState(state);}
function setNightTheme(dayId,nightTheme){if(!nightThemes.includes(nightTheme))throw new Error('Unknown night theme');const state=core.getState(),day=(state.menu?.days||[]).find(d=>d.id===dayId||String(d.day)===String(dayId));if(!day)throw new Error('Charter day not found');day.nightTheme=nightTheme;const dinner=day.meals?.dinner?.[0];if(!dinner?.locked){const replacement=chooseDinner(state.menu?.theme||'Mediterranean',nightTheme,Math.max(0,(day.day||1)-1),activeAllergies(state));if(replacement)day.meals.dinner=[replacement];}return saveState(state);}
function recommendAlternatives(dishId,options={}){const state=core.getState(),ctx=findDishContext(state,dishId);if(!ctx)throw new Error('Dish not found');const allergies=activeAllergies(state),currentTheme=state.menu?.theme||'Mediterranean',nightTheme=ctx.meal==='dinner'?(ctx.day.nightTheme||'Chef’s Choice'):'';const wantedCategories=new Set((Array.isArray(options.categories)?options.categories:[options.category]).filter(Boolean).map(normal)),wantedTags=new Set((options.tags||[]).map(normal)),count=Math.min(8,Math.max(3,Math.round(Number(options.count||5))));return allLibrary().filter(c=>c.meal===ctx.meal&&c.name!==ctx.dish.name&&!conflicts(c,allergies)).map(c=>{let score=0,reasons=[];const focus=sourceFocus(c),focusNorm=focus.map(normal);if(c.theme===currentTheme){score+=10;reasons.push('Matches charter style');}if(nightTheme!=='Chef’s Choice'&&(c.nightTheme===nightTheme||c.theme===nightTheme)){score+=28;reasons.push(`Matches ${nightTheme}`);}if(wantedCategories.size&&focusNorm.some(x=>wantedCategories.has(x))){score+=24;reasons.push('Matches sourcing category');}if(wantedTags.size&&(c.tags||[]).map(normal).some(x=>wantedTags.has(x))){score+=16;reasons.push('Matches available ingredient type');}if(options.location){score+=2;reasons.push(`Suitable for ${options.location}`);}if(options.preferredSupplier){score+=3;reasons.push(`Can use ${options.preferredSupplier}`);}return{...clone(c),sourceFocus:focus,score,reasons};}).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,count);}
function replaceDish(dishId,candidateName){const state=core.getState(),ctx=findDishContext(state,dishId);if(!ctx)throw new Error('Dish not found');if(ctx.dish.locked)throw new Error('Unlock the dish before replacing it');const allergies=activeAllergies(state);let pool=allLibrary().filter(d=>d.meal===ctx.meal&&!conflicts(d,allergies)&&d.name!==ctx.dish.name);if(candidateName){const exact=pool.find(d=>d.name===candidateName);if(!exact)throw new Error('That alternative is not available or conflicts with guest requirements');pool=[exact];}else if(ctx.meal==='dinner'&&ctx.day.nightTheme&&ctx.day.nightTheme!=='Chef’s Choice'){const themed=pool.filter(d=>d.nightTheme===ctx.day.nightTheme||d.theme===ctx.day.nightTheme);if(themed.length)pool=themed;}else{const sameTheme=pool.filter(d=>d.theme===(state.menu?.theme||'Mediterranean'));if(sameTheme.length)pool=sameTheme;}if(!pool.length)throw new Error('No alternative safe dish available');const pick=pool[Math.floor(Math.random()*pool.length)];const replacement=materialize(pick);for(const[id,items]of Object.entries(ctx.day.meals||{})){if(id!==ctx.meal)continue;const idx=items.findIndex(d=>d.id===dishId);items[idx]=replacement;}return saveState(state);}
function validate(){const state=core.getState(),allergies=activeAllergies(state),issues=[];for(const day of state.menu?.days||[]){for(const[meal,items]of Object.entries(day.meals||{})){for(const dish of items||[]){const hits=(dish.allergens||[]).filter(a=>allergies.has(normal(a)));if(hits.length)issues.push({day:day.day,meal,dishId:dish.id,dish:dish.name,allergens:hits});}}}return issues;}
function getThemes(){return Object.keys(library);}
function getNightThemes(){return clone(nightThemes);}
global.BusinessFlowMenu=Object.freeze({generate,setTheme,setNightTheme,toggleLock,replaceDish,recommendAlternatives,validate,getThemes,getNightThemes});
})(window);