(function(global){
'use strict';
const core=global.BusinessFlowCore;
if(!core)return;
const clone=v=>JSON.parse(JSON.stringify(v));
const norm=v=>String(v||'').trim().toLowerCase();
const roundQty=n=>{const x=Math.round(Number(n||0)*100)/100;return Number.isInteger(x)?x:Number(x.toFixed(2));};

const profiles={
  breakfastYoghurt:{portion:'1 breakfast bowl',prepMin:12,cookMin:0,totalMin:12,equipment:['mixing bowl','small knife','serving bowls'],temp:'Serve chilled',hold:'Best assembled within 10 minutes of service so granola stays crisp.',makeAhead:'Wash and dry berries up to 4 hours ahead. Keep chilled.',costBand:'€',ingredients:[['Greek yoghurt',180,'g'],['mixed berries',100,'g'],['granola',45,'g'],['honey',10,'g'],['mint',2,'leaves']],steps:[['PREP','Wash and completely dry the berries. Cut only large strawberries into bite-size pieces.','Berries should be dry and glossy, not sitting in water.'],['ASSEMBLE','Spoon yoghurt into a cold bowl, keeping the surface loose rather than flattened.','The yoghurt should look soft and natural, not packed down.'],['FINISH','Add berries, then granola, then a thin drizzle of honey. Finish with mint.','Granola remains visibly dry and crisp.']],plating:'Keep the yoghurt visible on one side, fruit grouped rather than scattered, granola added last.',substitutions:['Use coconut yoghurt for dairy-free.','Use seed granola when nut-free.'],leftovers:'Keep unassembled components separately. Do not store granola on wet yoghurt.'},
  omelette:{portion:'1 omelette',prepMin:8,cookMin:7,totalMin:15,equipment:['non-stick frying pan','whisk','rubber spatula'],temp:'Serve immediately',hold:'Do not hold cooked omelette; quality drops within minutes.',makeAhead:'Chop herbs and tomatoes up to 2 hours ahead.',costBand:'€',ingredients:[['eggs',3,''],['butter',10,'g'],['mixed soft herbs',5,'g'],['cherry tomatoes',80,'g'],['sourdough',1,'slice']],steps:[['PREP','Crack eggs into a bowl, season lightly and whisk only until yolk and white are combined.','Mixture is even yellow with no long strands of white.'],['COOK','Heat pan over medium-low heat, melt butter without browning, add eggs and stir gently while pulling soft curds toward the centre.','Egg remains glossy and softly set, never dry or browned.'],['FOLD','Stop stirring while surface is still slightly wet, add herbs, fold in half and slide onto plate.','Centre should be tender and moist, not runny.'],['FINISH','Serve with warmed tomatoes and toasted sourdough.','Plate is hot and omelette reaches table immediately.']],plating:'Place omelette slightly off-centre, tomatoes beside it, toast leaning rather than covering the omelette.',substitutions:['Use olive oil instead of butter for dairy-free.','Use gluten-free toast if required.'],leftovers:'Cooked omelette is not suitable for reuse; only unused prepared garnish should be retained safely.'},
  chilledPot:{portion:'1 breakfast pot',prepMin:10,cookMin:0,totalMin:10,equipment:['mixing bowl','serving glasses'],temp:'Serve chilled',hold:'Can hold refrigerated up to 4 hours once assembled.',makeAhead:'Base can be made the night before.',costBand:'€',ingredients:[['prepared chia or bircher base',180,'g'],['fresh fruit',100,'g'],['lime or lemon',5,'ml'],['toasted seeds',12,'g']],steps:[['PREP','Check the chilled base. Loosen with a small amount of milk or plant milk if it has become very firm.','It should spoon easily and hold a soft mound.'],['FRUIT','Cut fruit into even bite-size pieces and lightly dress with citrus.','Fruit looks fresh with clean edges, not crushed.'],['ASSEMBLE','Layer base and fruit without pressing them together. Add seeds only at the end.','Layers remain visible and seeds remain dry.']],plating:'Use a chilled clear glass or bowl so the layers are visible.',substitutions:['Use certified gluten-free oats for gluten-free bircher.','Use coconut or oat milk as needed.'],leftovers:'Keep base covered and refrigerated. Add fresh fruit and seeds only at service.'},
  fishLunch:{portion:'1 plated main',prepMin:25,cookMin:14,totalMin:39,equipment:['chef knife','fish tweezers','non-stick or stainless pan','fish slice','probe thermometer'],temp:'Fish: 52–56°C centre for moist flakes; follow vessel/company food-safety policy.',hold:'Do not hot-hold delicate fish longer than 5 minutes.',makeAhead:'Vegetables/salad components may be prepared 2–4 hours ahead; cook fish to order.',costBand:'€€',ingredients:[['fish fillet',180,'g'],['olive oil',12,'ml'],['lemon',0.25,''],['vegetables or salad garnish',160,'g'],['fine salt',2,'g'],['fresh herbs',4,'g']],steps:[['CHECK','Run fingertips over the fillet and remove every pin bone. Pat the fish completely dry.','Surface feels dry and no pin bones catch your fingers.'],['SEASON','Season lightly on both sides immediately before cooking.','Salt is even; no heavy patches.'],['COOK','Heat pan to medium-high, add oil, place presentation side down and do not move until a golden crust forms. Turn once and finish gently.','Fish releases from the pan with little resistance and flakes separate cleanly when pressed.'],['REST','Rest 2 minutes away from direct heat. Add lemon only after cooking unless recipe specifies otherwise.','Juices stay in the fish rather than flooding the plate.'],['PLATE','Place vegetable/salad base first, fish on top or alongside, sauce last.','Fish remains the visual focus and skin/crust stays clear of wet sauce.']],plating:'Build the garnish first. Place fish last so it stays hot and intact.',substitutions:['Swap sea bass/cod/salmon for another firm fillet of similar thickness and adjust cooking time.'],leftovers:'Unserved cooked fish should only be reused according to food-safety policy; chilled cooked fish can become staff salad or fish cakes if rapidly cooled.'},
  chickenMain:{portion:'1 plated main',prepMin:25,cookMin:22,totalMin:47,equipment:['chef knife','heavy frying pan','tongs','probe thermometer'],temp:'Cook poultry to the safe internal temperature required by your food-safety policy.',hold:'Rest 5–8 minutes after cooking; avoid holding longer than 15 minutes.',makeAhead:'Trim and portion chicken up to 6 hours ahead, refrigerated.',costBand:'€€',ingredients:[['chicken breast or supreme',190,'g'],['olive oil',12,'ml'],['lemon',0.2,''],['vegetable garnish',170,'g'],['fresh herbs',4,'g'],['fine salt',2,'g']],steps:[['PREP','Trim excess sinew and make portions an even thickness so they finish together. Pat dry.','Each portion is similar thickness and surface is dry.'],['SEASON','Season evenly just before cooking.','Seasoning is light and uniform.'],['SEAR','Heat pan, add oil and place chicken presentation side down. Leave it untouched until properly golden.','Chicken lifts from pan easily and has even golden colour.'],['FINISH','Turn, lower heat and finish gently. Check the thickest point with a clean probe.','Meat feels springy, juices are clear and required safe temperature is reached.'],['REST','Rest before slicing or plating.','Juices remain inside when the meat is cut.'],['PLATE','Plate hot garnish first, chicken second, sauce around rather than over crisp surfaces.','Plate looks clean and chicken is not swimming in sauce.']],plating:'Slice only if the design requires it; otherwise keep the portion whole for better moisture retention.',substitutions:['Turkey supreme can replace chicken with timing adjusted for thickness.'],leftovers:'Rapidly cool safe unused cooked chicken for staff meal, sandwiches or salad the next day according to food-safety policy.'},
  fruitSnack:{portion:'1 snack portion',prepMin:12,cookMin:0,totalMin:12,equipment:['chef knife','small bowls or tray'],temp:'Serve chilled',hold:'Best within 60 minutes of cutting.',makeAhead:'Whole fruit can be washed and chilled in advance.',costBand:'€',ingredients:[['seasonal fruit',180,'g'],['lime',0.15,''],['mint',3,'leaves']],steps:[['PREP','Wash fruit and dry it fully. Remove peel, seeds or stones as required.','Fruit is clean and dry before cutting.'],['CUT','Cut into consistent one-bite pieces so guests do not need a knife.','Pieces are even and undamaged.'],['FINISH','Add a very small amount of lime and torn mint just before service.','Fruit tastes fresh; citrus does not dominate.']],plating:'Use a cold shallow bowl or small cup, mixing colours rather than grouping all of one fruit.',substitutions:['Use whatever ripe seasonal fruit is best locally.'],leftovers:'Keep uncut fruit. Cut fruit should be refrigerated promptly and used within your food-safety window.'},
  savourySnack:{portion:'1 snack plate',prepMin:18,cookMin:0,totalMin:18,equipment:['chef knife','small tray','piping bag optional'],temp:'Serve cool',hold:'Assemble no more than 30 minutes before service.',makeAhead:'Dips/fillings may be prepared several hours ahead.',costBand:'€',ingredients:[['fresh vegetables',140,'g'],['dip or filling',60,'g'],['fresh herbs',3,'g']],steps:[['PREP','Wash, dry and trim vegetables. Cut each piece so it can be eaten neatly in one or two bites.','Vegetables are crisp, dry and evenly cut.'],['FILL','Spoon or pipe dip neatly; keep rims and edges clean.','Filling is contained and does not spill onto the service tray.'],['FINISH','Add herbs at the last moment and wipe the plate before it leaves the galley.','Every piece looks deliberate and easy to pick up.']],plating:'Leave enough negative space that guests can lift each piece without touching the others.',substitutions:['Use hummus, whipped feta, avocado or bean dip depending on allergy/dietary needs.'],leftovers:'Keep dip and unused vegetables separately refrigerated; do not return guest-handled items to stock.'},
  fishDinner:{portion:'1 plated dinner main',prepMin:35,cookMin:18,totalMin:53,equipment:['fish tweezers','chef knife','heavy pan','small saucepan','whisk','probe thermometer'],temp:'Fish: moist, just-flaking centre; sauce hot but not boiling after butter is added.',hold:'Fish: maximum ~5 minutes. Butter sauce: hold warm, never boil.',makeAhead:'Vegetable prep and sauce reduction can be completed well before service; mount sauce and cook fish close to service.',costBand:'€€€',ingredients:[['sea bass or similar fish fillet',180,'g'],['mixed seasonal vegetables',170,'g'],['dry white wine',35,'ml'],['white wine vinegar',8,'ml'],['shallot',18,'g'],['cold unsalted butter',45,'g'],['olive oil',10,'ml'],['lemon',0.2,''],['fine salt',2,'g']],steps:[['PREP FISH','Check every fillet for pin bones, trim ragged edges and pat completely dry. Keep refrigerated until the firing window.','Fillets are even, dry and free of bones.'],['SAUCE BASE','Put shallot, wine and vinegar in a small pan. Simmer until only a spoonful of liquid remains.','Reduction is syrupy and shallot is soft; pan is not dry.'],['VEGETABLES','Prepare vegetables into even sizes and blanch or pre-cook anything that cannot finish quickly at service.','All vegetables can finish together during the final firing window.'],['FIRE FISH','Heat pan medium-high, add oil, place fish skin/presentation side down. Press gently for the first 15–20 seconds to prevent curling, then leave it alone until crisp.','Skin is evenly golden and fish is mostly opaque up the sides before turning.'],['FINISH FISH','Turn, lower heat and finish gently. Rest briefly off the heat.','Centre separates into moist flakes with gentle pressure; it is not translucent/raw and not dry.'],['MOUNT SAUCE','Take reduction to very low heat. Whisk in cold butter a few cubes at a time. Do not boil once butter is going in. Season and add a small squeeze of lemon.','Sauce is glossy and coats the back of a spoon; no oily split around the edges.'],['PLATE','Place vegetables first. Add fish with crisp side visible. Spoon sauce around the fish, not over the crisp skin. Wipe rim and serve immediately.','Crisp skin stays dry, sauce is glossy, plate is hot and clean.']],plating:'Vegetables form a compact base, fish sits slightly off-centre, sauce forms a controlled pool around it. Finish with a small herb element only if it adds flavour.',substitutions:['Cod, bream, snapper or halibut can replace sea bass; adjust cook time for thickness.','For dairy-free, replace beurre blanc with lemon-herb olive oil or a stable dairy-free emulsion.'],leftovers:'Unused raw fish remains labelled/chilled. Safe unserved cooked fish may be rapidly cooled for staff use; do not hold and re-serve delicate fish as a guest main.'},
  lambBeef:{portion:'1 plated dinner main',prepMin:35,cookMin:24,totalMin:59,equipment:['heavy frying pan','tongs','small roasting tray','probe thermometer'],temp:'Cook to the guest-requested doneness while meeting applicable food-safety requirements.',hold:'Rest 6–10 minutes; keep warm but never tightly covered so crust stays intact.',makeAhead:'Trim and portion meat, prepare purée/vegetables and reduce jus in advance.',costBand:'€€€',ingredients:[['lamb loin or beef fillet',190,'g'],['olive oil',10,'ml'],['butter',12,'g'],['garlic',1,'clove'],['thyme',2,'sprigs'],['starch or vegetable garnish',180,'g'],['jus',45,'ml'],['fine salt',2,'g']],steps:[['TEMPER','Remove portions from the coldest part of the refrigerator shortly before cooking, within safe handling limits. Pat dry.','Surface is dry and portions are evenly shaped.'],['SEASON','Season all sides immediately before searing.','Salt coverage is even.'],['SEAR','Use a properly hot pan with a thin film of oil. Sear all presentation surfaces until deeply coloured.','A brown crust develops without black burnt patches.'],['BASTE','Lower heat, add butter, garlic and thyme. Tilt pan and spoon foaming butter over the meat.','Butter foams and smells nutty but is not black.'],['CHECK','Use touch plus a clean probe to confirm the requested doneness.','Centre temperature matches the intended doneness; exterior is well coloured.'],['REST','Rest on a rack or warm plate before slicing.','Very little juice runs out when sliced.'],['PLATE','Plate hot garnish and jus first where appropriate, slice meat cleanly across the grain only at the last moment.','Slices are clean and glossy; plate remains hot.']],plating:'Keep the meat as the focus. Do not cover the seared surface with sauce.',substitutions:['Venison loin can follow the same method with careful timing.','Use olive oil instead of butter if dairy-free.'],leftovers:'Rapidly cool safe unserved meat for staff meal, sandwiches or next-day hash according to food-safety policy.'},
  prawnMain:{portion:'1 plated dinner main',prepMin:25,cookMin:8,totalMin:33,equipment:['paring knife','frying pan','tongs'],temp:'Cook until flesh is opaque and just firm.',hold:'Serve immediately; prawns toughen quickly when held hot.',makeAhead:'Peel/devein and prepare garnish in advance; cook at service.',costBand:'€€€',ingredients:[['large prawns',180,'g'],['olive oil',12,'ml'],['garlic',0.5,'clove'],['lemon',0.25,''],['courgette or vegetable garnish',170,'g'],['fresh herbs',4,'g']],steps:[['PREP','Peel and devein prawns if required. Pat completely dry.','No shell fragments or dark vein remain.'],['SEASON','Season immediately before cooking.','Prawns stay dry rather than weeping liquid.'],['COOK','Heat pan until hot, add oil, add prawns in one layer and cook without overcrowding. Turn once.','Prawns change from translucent to opaque and form a loose C-shape, not a tight O.'],['FINISH','Add garlic/herbs only near the end so they do not burn. Finish with lemon off the heat.','Garlic smells sweet, not bitter, and prawns remain juicy.'],['PLATE','Plate garnish first and prawns last. Serve straight away.','Prawns are glossy and hot with no watery liquid on plate.']],plating:'Arrange prawns in a deliberate arc or small group rather than scattering them.',substitutions:['Scallops can be used with a different searing time.'],leftovers:'Do not hot-hold. Rapidly cool safe unserved cooked shellfish for staff use according to policy.'}
};

const dishProfile=new Map([
['Greek yoghurt, berries & pistachio granola','breakfastYoghurt'],['Fresh fruit, yoghurt & toasted seeds','breakfastYoghurt'],
['Herb omelette, tomatoes & sourdough','omelette'],['Poached eggs, spinach & rye toast','omelette'],
['Apple bircher, seeds & berries','chilledPot'],['Chia, mango & lime breakfast pot','chilledPot'],
['Citrus sea bass, fennel & new potatoes','fishLunch'],['Roast salmon, peas, asparagus & dill','fishLunch'],['Grilled tuna, tomato, olive & herb salad','fishLunch'],
['Lemon chicken, charred courgette & couscous','chickenMain'],['Chicken supreme, crushed potatoes & greens','chickenMain'],['Chicken, avocado & citrus salad','chickenMain'],['Herb chicken, ratatouille & basil oil','chickenMain'],
['Watermelon, mint & feta cups','fruitSnack'],['Seasonal fruit & coconut yoghurt','fruitSnack'],['Berry smoothie & oat bites','fruitSnack'],['Frozen grapes, berries & melon','fruitSnack'],
['Crudités, hummus & seeded crackers','savourySnack'],['Cucumber cups with avocado & herbs','savourySnack'],
['Pan-roasted sea bass, beurre blanc & vegetables','fishDinner'],['Roast cod, leeks & herb velouté','fishDinner'],
['Herb lamb loin, aubergine & tomato jus','lambBeef'],['Beef fillet, pommes purée & red wine jus','lambBeef'],
['Grilled prawns, courgette ribbons & lemon','prawnMain']
]);

function visualFor(name,meal){
  const n=norm(name);let protein='PLATED';
  if(/fish|bass|cod|salmon|tuna/.test(n))protein='FISH';else if(/chicken/.test(n))protein='POULTRY';else if(/lamb|beef/.test(n))protein='MEAT';else if(/prawn/.test(n))protein='SHELLFISH';else if(/yoghurt|bircher|chia|fruit/.test(n))protein='FRESH';else if(/omelette|egg/.test(n))protein='EGG';
  return {protein,meal:meal||'',caption:'PLATING PREVIEW'};
}
function findDish(dishId){
  const state=core.getState();
  for(const day of state.menu?.days||[]){for(const [meal,items] of Object.entries(day.meals||{})){for(const dish of items||[]){if(dish.id===dishId)return {...clone(dish),day:day.day,date:day.date,meal};}}}
  return null;
}
function firstDish(){const s=core.getState();for(const day of s.menu?.days||[]){for(const meal of ['breakfast','lunch','snack','dinner']){if(day.meals?.[meal]?.[0])return {...clone(day.meals[meal][0]),day:day.day,date:day.date,meal};}}return null;}
function profileFor(dish){
  const key=dishProfile.get(dish?.name)||(/dinner/.test(dish?.meal||'')?'fishDinner':/lunch/.test(dish?.meal||'')?'chickenMain':/snack/.test(dish?.meal||'')?'fruitSnack':'chilledPot');
  return clone(profiles[key]);
}
function scaledIngredients(profile,guests){return profile.ingredients.map(([name,qty,unit])=>({name,qty:roundQty(Number(qty)*guests),unit}));}
function getRecipe(dishId){
  const state=core.getState(),dish=findDish(dishId)||firstDish();if(!dish)return null;
  const guests=Math.max(1,Number(state.charter.guestCount||1)),profile=profileFor(dish);
  return {dish,guests,portion:profile.portion,prepMin:profile.prepMin,cookMin:profile.cookMin,totalMin:profile.totalMin,equipment:profile.equipment,temperature:profile.temp,hold:profile.hold,makeAhead:profile.makeAhead,costBand:profile.costBand,ingredients:scaledIngredients(profile,guests),steps:profile.steps.map((s,i)=>({number:i+1,phase:s[0],instruction:s[1],cue:s[2]})),plating:profile.plating,substitutions:profile.substitutions,leftovers:profile.leftovers,allergens:clone(dish.allergens||[]),visual:visualFor(dish.name,dish.meal)};
}
function buildServiceSteps(recipe,serviceTime){
  if(!recipe)return[];
  const total=Math.max(10,recipe.totalMin||30),count=recipe.steps.length;
  return recipe.steps.map((step,i)=>({id:`recipe_${recipe.dish.id}_${i+1}`,offsetMin:Math.max(0,Math.round(total-(i*(total/Math.max(1,count-1))))),label:`${recipe.dish.name}: ${step.phase}`,status:'pending',instruction:step.instruction,cue:step.cue}));
}

global.BusinessFlowRecipes=Object.freeze({getRecipe,findDish,firstDish,buildServiceSteps});
})(window);